server.port = 8082

spring.datasource.url=jdbc:mysql://localhost:3306/moviematrix
spring.datasource.username=root
spring.datasource.password=Soumi@1204_Mon

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

tmdb.api.key=92a9ad8259d247a88b8326d2ab8e7a0e
tmdb.base.url=https://api.themoviedb.org/3
tmdb.image.base.url=https://image.tmdb.org/t/p/w500